#!/bin/bash

CONFIG=$(dirname $0)/../config.json
APPNAME=$( jq -r < $CONFIG '.appname')
REGION=$(  jq -r < $CONFIG '.region')
REGISTRY=$(jq -r < $CONFIG '.registry')

# Create the CloudWatch log group, if necessary:
GRPNAME="/ecs/${APPNAME}"
if [ 0 -eq $(aws logs describe-log-groups --log-group-name-prefix "$GRPNAME" | jq '.logGroups | length') ]
then aws logs create-log-group --log-group-name "$GRPNAME"
fi

json=$(mktemp /tmp/$(basename $0)_XXXXX)

cat <<EOT > $json
{
  "family": "${APPNAME}-task",
  "taskRoleArn": "ECS-Task-DynamoDB",
  "executionRoleArn": "ecsTaskExecutionRole",
  "networkMode": "awsvpc",
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "cpu": "256",
  "memory": "512",
  "containerDefinitions": [
    {
      "name": "${APPNAME}",
      "image": "${REGISTRY}/${APPNAME}:latest",
      "cpu": 256,
      "memory": 512,
      "entryPoint": [],
      "essential": true,
      "portMappings": [
        {
          "hostPort": 8080,
          "protocol": "tcp",
          "containerPort": 8080
        }
      ],
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "${GRPNAME}",
          "awslogs-region": "${REGION}",
          "awslogs-stream-prefix": "ecs"
        }
      }
    }
  ]
}
EOT

# Filter thru jq to syntax-check the json before passing to the AWS CLI.
if   jq < $json > /dev/null
then aws ecs register-task-definition --cli-input-json file://$json
fi

