#!/bin/bash

CONFIG=$(dirname $0)/../config.json
APPNAME=$( jq -r < $CONFIG '.appname')
REGION=$(  jq -r < $CONFIG '.region')
REGISTRY=$(jq -r < $CONFIG '.registry')

# This VPC should be created automatically when you create your default ECS cluster.
VPC=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=ECS default - VPC" | jq -r '.Vpcs[0].VpcId')
SUBNETS=$(aws ec2 describe-subnets         --filters "Name=vpc-id,Values=$VPC" | jq -c '.Subnets | map(.SubnetId)')
SECGRPS=$(aws ec2 describe-security-groups --filters "Name=vpc-id,Values=$VPC" | jq -c '.SecurityGroups | map(.GroupId)')

json=$(mktemp /tmp/$(basename $0)_XXXXX)

cat <<EOT > $json
{
    "desiredCount": 1,
    "launchType": "FARGATE",
    "schedulingStrategy": "REPLICA",
    "serviceName": "${APPNAME}-service",
    "taskDefinition": "${APPNAME}-task",
    "networkConfiguration": {
        "awsvpcConfiguration": {
            "subnets": ${SUBNETS},
            "securityGroups": ${SECGRPS},
            "assignPublicIp": "ENABLED"
        }
    }
}
EOT

if   jq < $json > /dev/null
then aws ecs create-service --cli-input-json file://$json
fi

