#!/bin/bash

COUNT=${1:?Please specify the desired count}

CONFIG=$(dirname $0)/../config.json
APPNAME=$( jq -r < $CONFIG '.appname')
REGION=$(  jq -r < $CONFIG '.region')

aws ecs update-service --service "${APPNAME}-service" --desired-count $COUNT


